### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by harley** [con-beo-vang/Spendy#1]
Due date:  Tuesday, September 15th
- [x] Create your organization and project
- [x] Create an organization on Github
- [x] Add each team member in your group to the organization
- [x] Generate a new Xcode project for your group. 
- [x] Push the repository to your new project organization. https://github.com/con-beo-vang/Spendy
- [x] Sketch out functional user stories
- [x] Add a README to your project repo with the following elements:
  - [x] Paragraph that describes your app and what it does
  - [x] Required (core) user stories for your app in a bulleted list
  - [x] Optional (nice to have) user stories listed separately
- [x] Create simple wireframes for your app
- [x] Choose [[wireframing tools]] or use pen and paper to create the app screens
- [x] Draw out each screen with key elements (action bar items, input fields, list item display, data shown)
- [x] Be sure to identify the core flow between screens within your app --> See invision
- [x] Your app should have at least 3 distinct screens so think about the various archetypes
- [x] Add the wireframes to your project repo on Github (either uploading the files or linking to them from the README)

**Comment by harley** [comment]
Milestone 1 submitted by @minhchau273 and myself.
@chug2k please review :)
(Note: screen 2 in Wireframe should use a numeric keyboard instead)

**Comment by chug2k** [comment]
This is amazing work with the wireframes and Invision. Great job separating out the stories! 

Despite all this good work...I am not so sure about this idea. Maybe we can talk about this in person later tonight, but my question is: why? Why would anyone want to do this? I am missing the story here. I also am very skeptical that people would remember to use this all the time. One way to answer this question is to try and "use" this app yourself - maybe prototype it using the notes application by just pulling out your phone and noting every time you use money. I am almost 100% sure that you can do this for one day, maybe two, but on the third day you will start forgetting to use it. The push notifications could help a little bit, but I am sure you will start ignoring them after the third or fourth day.

One way to add "story" into something like this is to make it more "fun" and "social" - I think Lozi is a good example of a way to make people _want_ to use an app regularly. You could also think about maybe adding more "story" by giving it a theme: perhaps this is to help people lose weight, or to help people set a goal for spending every month? 

Lastly, scope wise, I do not know what "expense accounts" are. In the wireframes you seem to be connected to an actual bank account? This would be quite difficult. 

Perhaps one thing I should've asked for is a quick competitive analysis. Are there any apps like yours currently available? What are their strengths/weaknesses? Why is your app better?

For you, I'd guess Mint.com is a good competitor, but I am sure there are 1,000 other "track your spending" apps. What makes them special?

**Comment by harley** [comment]
Thank you for an early and thorough review! Just some quick notes at my lunch break (sorry if rambling)

We actually wanted to build this expense tracking app for ourselves because the expense input process isn't convenient on apps we have tried and it is easy to forget.

1/ Re: habit. We aim to make people keep using the expense app by 
  a) to-the-point push notification via banner or lock screen: adding a regular expense should be as easy as dismissing a notification. iOS support for button in notification message may be limited but we wanted to explore this.
  b) we prioritize not forgetting an expense over the accuracy of an expense. Spend 45,500 VND? Just tap "50K" and forget about the change.
  b) the wireframe does not show it but when we mock it up, we hope to show inputing via taps and other gestures will be better than using a numerical keypad.

2/ Re: accounts. We do not intend to connect to bank accounts but rather, it is just a rough estimate. I would only use my Cash account but Chau does keep track of her payment or cash withdrawals via an expense app. I think a Saving account on Spendy can include transactions of multiple actual bank saving accounts I have? Vietnamese banks actually don't show you the expenses easily online and many only keep up to 3 months.

3/ Goal is a good point. Perhaps I aim to spend less than 1 million on meal a month? I think it may be better to requires a minimum spending goal too because that way, people are reminded to enter their expenses.

Hope item 1 above covers what our app will do better. There are a lot of expense apps out there but they are either ugly and poorly done (old tech), ad-supported (annoying) or too complicated (paid).

Unlike categories such as todo, messaging, fitness, etc where there are both elegantly simple and beautifully complex apps. In expense tracking, we don't see any elegantly simple app yet (only boringly functional ones).

Thank you again for challenging these. We are definitely open to all critiques to further evaluate.

**Comment by chug2k** [comment]
Okay, I am more convinced. I especially do like the rough estimate of how much money you spend. I can almost see the demo: you can ask the audience how much money did you spend this week? Most people have no idea. (I have no idea.)  But if I knew like, oh, around 300k VND then maybe that would be cool. (But then, I'm still wondering why? If I cared about knowing how much I spent, I would have kept track of it, no?)

I would love to see:
1. Other expense apps that are ugly, annoying, or complicated
2. Todo/fitness apps that you are inspired by

I think maybe one class of apps similar to yours could be https://open.bufferapp.com/build-strong-habits-apps-tools/ (I just googled "habit forming ios apps"). 

Regardless, part of the grading criteria will be technical excellence, and I'm sure you will do very well on that, I'm just worried about usefulness. 

Perhaps you can try and prototype the push notifications more quickly. One very "lean" idea would be to just set an alarm on your phone for 12:00 or whenever the push notification will be sent, and then to use the note taking app. Or for one step higher, you could text each other (Harley <=> Chau) and say "how much did you spend" and just reply in SMS.
