### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by harley** [con-beo-vang/Spendy#9]
Due: Tuesday, September 22
## Required:
- [x] Set up and configure Parse for server-side data store. Download this [config key](https://www.dropbox.com/s/uzaecpnmh4suzd9/Config.plist?dl=0) and drop it in the `Spendy/Spendy` folder. Password is @chug2k's phone number. This file is protected because this is a public repo.
- [x] Design database schema ([gdoc](https://docs.google.com/document/d/1imOU9yNGimVjELrXHZfrRf5uOdYAjWnvIU4rS3TO-88/edit))
- [x] View controllers for early functionality and GIF walkthroughs (see below) 
- [x] A survey for the project idea. ([questions](http://ht.gl/ioswk))
## Considerations
- [x] Product pitch: 
  What is harder than keeping track of your calorie intake? Keeping track of your money! Still haven't found your favorite app for that? Spendy helps you manage your daily expenses painlessly. Enter your most frequently used expenses via smart reminders and simple gestures. Never forget entering your expense again!
- [x] Key audience: young iOS users who are addicted to their phones. They will use this to track their daily spending on common categories such as meals, drinks and commute because it has been too easy to forget doing so, until now!
- [x] Core flows:
  - Key functions: add an expense from notification screen, add an expense/income by swiping, set up reminders for categories
  - Main screens: four main screens (home, accounts, settings, and add)
- [ ] [ongoing] Final demo: TBD
- [x] Mobile features: push notifications, gestures, reminders, and potentially camera.
- [ ] [ongoing] Technical concerns: how to make a good use of iOS notifications. All current notifications from apps are boring messages (except maybe Foursquare's: are you back to Sushi place? Check in right away?)
## Quick competitive analysis

We do not intend to have a thorough one, but a rough document is maintained here [gdoc](https://docs.google.com/document/d/1lQg8ykg1E-0MPWpOiesJKQf6AJvfOm7AV478t7P59hE/edit?usp=sharing)
### Home page

![](https://raw.githubusercontent.com/con-beo-vang/Spendy/master/Home.gif)
### Settings page

![](https://raw.githubusercontent.com/con-beo-vang/Spendy/master/Settings.gif)
### Accounts page

![](https://raw.githubusercontent.com/con-beo-vang/Spendy/master/Accounts.gif)
### Quick Add

![](https://raw.githubusercontent.com/con-beo-vang/Spendy/master/QuickAdd.gif)
## Responses

Because this repo is public, the responses are not made public here. We also only asked a small sample. If you want the raw responses, request access [here](http://ht.gl/ioswkresults) :)

![screenshot 2015-09-22 09 25 20](https://cloud.githubusercontent.com/assets/44055/10009787/196a3b06-610c-11e5-8eb6-36f1134e99d4.png)

![screenshot 2015-09-22 09 27 58](https://cloud.githubusercontent.com/assets/44055/10009790/45a17108-610c-11e5-892e-9c9395f27720.png)

**Comment by harley** [comment]
@minhchau273 and I completed this week's milestone. @chug2k please review 🌋
